import { addDays, addMonths, nowIso, type Customer, type DomainRepository, type DomainState, type LedgerType, type PlanId, type Reseller, type User } from './types'
import { assertPermission } from './permissions'
import { additionalUpgradeCredits, downgradeRefund, expirationForPlan, planRules } from './plans'

const id = (prefix: string) => `${prefix}_${crypto.randomUUID()}`
const audit = (state: DomainState, actorUserId: string, action: string, targetType: string, targetId: string, details: Record<string, unknown>) => state.audits.push({ id: id('audit'), actorUserId, action, targetType, targetId, details, createdAt: nowIso() })
function ledger(state: DomainState, actorUserId: string, resellerId: string, type: LedgerType, quantity: number, reason: string, customerId?: string) { const reseller = state.resellers.find(x => x.userId === resellerId); if (!reseller || quantity === 0) throw new Error('Revendedor ou quantidade inválida'); const before = reseller.creditBalance; const after = before + quantity; if (after < 0) throw new Error('Créditos insuficientes'); reseller.creditBalance = after; state.ledger.push({ id: id('ledger'), resellerId, type, quantity, balanceBefore: before, balanceAfter: after, reason, customerId, actorUserId, createdAt: nowIso() }) }
function actor(state: DomainState, actorUserId: string) { const user = state.users.find(x => x.id === actorUserId); if (!user) throw new Error('Usuário não encontrado'); return user }

export async function createResellerCustomer(repo: DomainRepository, actorUserId: string, input: Pick<Customer, 'name' | 'username' | 'plan'> & { password: string }) { const state = await repo.getState(); const user = actor(state, actorUserId); assertPermission(user.role, 'customers:write'); if (user.role !== 'RESELLER') throw new Error('Somente revendedor pode criar cliente nesta operação'); const reseller = state.resellers.find(x => x.userId === actorUserId); if (!reseller) throw new Error('Perfil de revendedor não encontrado'); if (reseller.model === 'CUSTOMER_LIMIT') { if (reseller.cycleUsed >= (reseller.customerLimit ?? planRules.customerLimit)) throw new Error('Limite mensal de clientes atingido'); reseller.cycleUsed += 1 } else ledger(state, actorUserId, actorUserId, 'CUSTOMER_CREATION', -planRules.credits[input.plan], `Criação de cliente ${input.username}`); const createdAt = nowIso(); const customer: Customer = { id: id('customer'), userId: id('user'), name: input.name, username: input.username, plan: input.plan, customerSource: 'RESELLER', resellerId: actorUserId, createdAt, expiresAt: expirationForPlan(createdAt, input.plan), status: 'ACTIVE', passwordHash: `server-hash-required:${input.password.length}` }; state.customers.push(customer); audit(state, actorUserId, 'CUSTOMER_CREATED', 'customer', customer.id, { username: customer.username, source: customer.customerSource }); await repo.saveState(state); return customer }

export async function grantMonthlyCredits(repo: DomainRepository, actorUserId: string, resellerId: string, amount: number) { const state = await repo.getState(); const user = actor(state, actorUserId); assertPermission(user.role, 'credits:write'); ledger(state, actorUserId, resellerId, 'MONTHLY_CREDIT', amount, 'Crédito mensal acumulativo'); audit(state, actorUserId, 'MONTHLY_CREDITS_GRANTED', 'reseller', resellerId, { amount }); await repo.saveState(state) }
export async function changeCustomerPlan(repo: DomainRepository, actorUserId: string, customerId: string, nextPlan: PlanId, mode: 'UPGRADE' | 'DOWNGRADE') { const state = await repo.getState(); const user = actor(state, actorUserId); assertPermission(user.role, 'customers:write'); const customer = state.customers.find(x => x.id === customerId); if (!customer) throw new Error('Cliente não encontrado'); if (!customer.resellerId) throw new Error('Cliente sem revendedor'); if (mode === 'UPGRADE') ledger(state, actorUserId, customer.resellerId, 'PLAN_UPGRADE', -additionalUpgradeCredits(customer, nextPlan), 'Upgrade proporcional', customer.id); else ledger(state, actorUserId, customer.resellerId, 'PLAN_DOWNGRADE_REFUND', downgradeRefund(customer, nextPlan), 'Reembolso proporcional de downgrade', customer.id); customer.plan = nextPlan; customer.expiresAt = expirationForPlan(nowIso(), nextPlan); audit(state, actorUserId, `PLAN_${mode}`, 'customer', customer.id, { nextPlan }); await repo.saveState(state); return customer }
export async function generateResellerTest(repo: DomainRepository, actorUserId: string, customerId?: string) { const state = await repo.getState(); const user = actor(state, actorUserId); if (user.role !== 'RESELLER') throw new Error('Somente revendedores podem gerar testes'); ledger(state, actorUserId, actorUserId, 'OTHER', -1, 'Teste de 48 horas', customerId); const test = { id: id('test'), customerId, createdAt: nowIso(), expiresAt: addDays(nowIso(), 2), status: 'ACTIVE' as const }; state.tests.push(test); await repo.saveState(state); return test }
export async function grantTrustRenewal(repo: DomainRepository, actorUserId: string, customerId: string) { const state = await repo.getState(); const user = actor(state, actorUserId); if (user.role !== 'RESELLER') throw new Error('Somente revendedores podem renovar'); const customer = state.customers.find(x => x.id === customerId); if (!customer) throw new Error('Cliente não encontrado'); customer.expiresAt = addDays(customer.expiresAt, planRules.trustRenewalDays); customer.status = 'ACTIVE'; ledger(state, actorUserId, actorUserId, 'TRUST_RENEWAL', 0.001, 'Renovação de confiança +1 dia', customerId); audit(state, actorUserId, 'TRUST_RENEWAL', 'customer', customerId, {}); await repo.saveState(state); return customer }
export async function getExpirationState(repo: DomainRepository, customerId: string, salesUrl: string) { const state = await repo.getState(); const customer = state.customers.find(x => x.id === customerId); if (!customer) throw new Error('Cliente não encontrado'); const days = Math.ceil((new Date(customer.expiresAt).getTime() - Date.now()) / 86400000); const reseller = customer.resellerId ? state.resellers.find(x => x.userId === customer.resellerId) : undefined; return { expired: days <= 0, daysRemaining: days, warning: days === 2 ? 'TWO_DAYS' as const : days === 1 ? 'ONE_DAY' as const : undefined, renewalUrl: customer.customerSource === 'RESELLER' ? undefined : salesUrl, reseller: reseller ? { contactName: reseller.contactName, phone: reseller.phone } : undefined, blocking: days <= 0 } }

export async function recordLiveViewing(repo: DomainRepository, viewing: DomainState['liveViewing'][number]) { const state = await repo.getState(); const existing = state.liveViewing.find(x => x.userId === viewing.userId); if (existing) Object.assign(existing, viewing); else state.liveViewing.push(viewing); await repo.saveState(state) }
export async function requestCustomerDeletion(repo: DomainRepository, actorUserId: string, customerId: string, reason: string) { const state = await repo.getState(); const user = actor(state, actorUserId); assertPermission(user.role, 'customers:delete-request'); audit(state, actorUserId, 'CUSTOMER_DELETION_REQUESTED', 'customer', customerId, { reason }); await repo.saveState(state) }
export function getResellerAlert(reseller: Reseller) { if (reseller.model !== 'CUSTOMER_LIMIT') return null; const limit = reseller.customerLimit ?? planRules.customerLimit; const ratio = reseller.cycleUsed / limit; return ratio >= 1 ? 'LIMIT_REACHED' : ratio >= .95 ? 'LIMIT_475' : ratio >= .9 ? 'LIMIT_450' : ratio >= .8 ? 'LIMIT_400' : null }
