'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { contentService, formatDuration, mockChannels, mockMovies, mockSeries, type AnyContent, type Channel, type Movie, type Series } from '@/lib/content-service'

type View = 'Início' | 'Filmes' | 'Séries' | 'Canais' | 'Pesquisa' | 'Favoritos' | 'Configurações'
type MediaSource = { id: string; type: 'movie' | 'episode' | 'channel'; title: string; url: string; poster: string; duration?: number }

function Logo() { return <div className="brand-mark" aria-label="CirclePlay"><span className="brand-ring">C</span><span>Circle<span className="brand-accent">Play</span></span></div> }
function Icon({ name }: { name: string }) { return <span className="nav-icon" aria-hidden="true">{name}</span> }
function MediaCard({ item, onOpen, favorite, onFavorite, selected }: { item: Movie | Series; onOpen: () => void; favorite: boolean; onFavorite: () => void; selected?: boolean }) { return <article className={`media-card focusable ${selected ? 'selected' : ''}`} tabIndex={0} onClick={onOpen} onKeyDown={e => e.key === 'Enter' && onOpen()}><div className="media-image" style={{ backgroundImage: `url(${item.image})` }}><button className="favorite-mini" aria-label={favorite ? 'Remover favorito' : 'Adicionar favorito'} onClick={e => { e.stopPropagation(); onFavorite() }}>{favorite ? '★' : '☆'}</button>{item.badge && <span className="card-badge">{item.badge}</span>}{item.progress !== undefined && <div className="progress-track"><span style={{ width: `${item.progress}%` }} /></div>}<span className="play-overlay">▶</span></div><strong>{item.title}</strong><span className="card-meta">{item.year} · {'seasons' in item ? `${item.seasons} temporadas` : formatDuration(item.duration)}</span></article> }
function ChannelCard({ channel, onOpen, selected }: { channel: Channel; onOpen: () => void; selected?: boolean }) { return <article className={`channel-card focusable ${selected ? 'selected' : ''}`} tabIndex={0} onClick={onOpen} onKeyDown={e => e.key === 'Enter' && onOpen()}><div className="channel-image" style={{ backgroundImage: `url(${channel.image})` }}><span className={channel.status === 'live' ? 'live-dot' : 'time-chip'}>{channel.status === 'live' ? 'AO VIVO' : 'EM BREVE'}</span></div><strong>{channel.name}</strong><span className="card-meta">{channel.category} · {channel.current}</span></article> }
function Rail({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rail"><div className="rail-heading"><h2>{title}</h2><button className="see-all focusable">Ver todos <span>→</span></button></div><div className="rail-row">{children}</div></section> }

export default function CirclePlay() {
  const [loggedIn, setLoggedIn] = useState(false), [showPassword, setShowPassword] = useState(false), [view, setView] = useState<View>('Início'), [query, setQuery] = useState(''), [selected, setSelected] = useState<AnyContent | null>(null), [player, setPlayer] = useState<MediaSource | null>(null), [favorites, setFavorites] = useState<string[]>([]), [sidebarOpen, setSidebarOpen] = useState(true), [season, setSeason] = useState(1), [channelIndex, setChannelIndex] = useState(0)
  const lastFocus = useRef<Record<string, string>>({})
  useEffect(() => { try { setFavorites(JSON.parse(localStorage.getItem('circleplay-favorites') || '[]')) } catch {} }, [])
  const toggleFavorite = (id: string) => setFavorites(current => { const next = current.includes(id) ? current.filter(x => x !== id) : [...current, id]; localStorage.setItem('circleplay-favorites', JSON.stringify(next)); return next })
  useEffect(() => { const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape' || e.key === 'BrowserBack') { if (player) setPlayer(null); else if (selected) setSelected(null); else setView('Início') } if (player && (player.type === 'channel') && e.key === 'ArrowDown') setChannelIndex(i => Math.min(mockChannels.length - 1, i + 1)); if (player && player.type === 'channel' && e.key === 'ArrowUp') setChannelIndex(i => Math.max(0, i - 1)) }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [player, selected])
  const openContent = (item: AnyContent) => { setSelected(item); lastFocus.current[view] = item.id }
  const start = (item: Movie | Series | Channel) => { setSelected(null); setPlayer({ id: item.id, type: 'streamUrl' in item ? 'channel' : 'movie', title: item.title || item.name, url: 'streamUrl' in item ? item.streamUrl : `mock://${item.id}`, poster: item.image, duration: 'duration' in item ? item.duration : undefined } as MediaSource) }
  const searchResults = useMemo(() => { const q = query.toLowerCase(); return { movies: mockMovies.filter(x => x.title.toLowerCase().includes(q) || x.genre.toLowerCase().includes(q)), series: mockSeries.filter(x => x.title.toLowerCase().includes(q)), channels: mockChannels.filter(x => x.name.toLowerCase().includes(q)) } }, [query])
  if (!loggedIn) return <main className="login-screen"><section className="login-panel"><Logo /><h1>Entrar na sua conta</h1><p className="login-copy">Acesse seus filmes, séries e canais favoritos.</p><form onSubmit={e => { e.preventDefault(); setLoggedIn(true) }}><label>Usuário ou e-mail<input required placeholder="usuario@exemplo.com" /></label><label>Senha<div className="password-wrap"><input required minLength={4} type={showPassword ? 'text' : 'password'} placeholder="••••••••" /><button type="button" className="show-password" onClick={() => setShowPassword(!showPassword)}>{showPassword ? 'Ocultar' : 'Mostrar'}</button></div></label><button className="primary-button" type="submit">Entrar <span>→</span></button></form></section></main>
  const nav: { label: View | 'Sair'; icon: string }[] = [{ label: 'Início', icon: '⌂' }, { label: 'Filmes', icon: '▣' }, { label: 'Séries', icon: '▤' }, { label: 'Canais', icon: '◉' }, { label: 'Pesquisa', icon: '⌕' }, { label: 'Favoritos', icon: '★' }, { label: 'Configurações', icon: '⚙' }, { label: 'Sair', icon: '↪' }]
  const movies = view === 'Favoritos' ? mockMovies.filter(x => favorites.includes(x.id)) : mockMovies
  const series = view === 'Favoritos' ? mockSeries.filter(x => favorites.includes(x.id)) : mockSeries
  return <main className="iptv-shell"><aside className={`side-menu ${sidebarOpen ? 'open' : 'closed'}`}><button className="side-toggle focusable" onClick={() => setSidebarOpen(!sidebarOpen)}>{sidebarOpen ? '‹' : '›'}</button><Logo /><nav aria-label="Menu principal">{nav.map(item => <button key={item.label} className={`side-link focusable ${view === item.label ? 'active' : ''}`} onClick={() => item.label === 'Sair' ? setLoggedIn(false) : setView(item.label as View)}><Icon name={item.icon} />{sidebarOpen && <span>{item.label}</span>}</button>)}</nav></aside><section className="iptv-main"><header className="topbar"><button className="mobile-menu focusable" onClick={() => setSidebarOpen(!sidebarOpen)}>☰</button><div className="topbar-title"><span className="eyebrow">CIRCLEPLAY</span><strong>{view}</strong></div><div className="profile-area"><button className="search-trigger focusable" onClick={() => setView('Pesquisa')} aria-label="Pesquisar">⌕</button><button className="avatar focusable">MP</button></div></header>
  {view === 'Início' && <><section className="hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(7,11,20,.98), rgba(7,11,20,.7) 40%, rgba(7,11,20,.05)), url(${mockMovies[0].image})` }}><div className="hero-copy"><span className="hero-kicker">CIRCLEPLAY ORIGINAL</span><h1>{mockMovies[0].title}</h1><div className="hero-meta"><span>2024</span><span>16</span><span>{formatDuration(mockMovies[0].duration)}</span><span>{mockMovies[0].genre}</span></div><p>{mockMovies[0].description}</p><div className="hero-actions"><button className="primary-button focusable" onClick={() => start(mockMovies[0])}>▶&nbsp; Assistir</button><button className="secondary-button focusable" onClick={() => openContent(mockMovies[0])}>Mais informações</button></div></div></section><div className="content-wrap"><Rail title="Continuar assistindo">{mockMovies.filter(x => x.progress).map(x => <MediaCard key={x.id} item={x} onOpen={() => openContent(x)} favorite={favorites.includes(x.id)} onFavorite={() => toggleFavorite(x.id)} />)}</Rail><Rail title="Ao vivo agora">{mockChannels.slice(0, 8).map(x => <ChannelCard key={x.id} channel={x} onOpen={() => start(x)} />)}</Rail>{['Filmes populares','Filmes adicionados recentemente','Séries populares','Ação','Comédia','Terror','Animação','Favoritos'].map((title, i) => <Rail key={title} title={title}>{(i === 2 ? series : i === 7 ? [...movies, ...series] : movies).slice(i * 2, i * 2 + 8).map(x => <MediaCard key={x.id} item={x} onOpen={() => openContent(x)} favorite={favorites.includes(x.id)} onFavorite={() => toggleFavorite(x.id)} />)}</Rail>)}</div></>}
  {view === 'Filmes' && <Library title="Filmes" items={movies} categories={['Todos','Populares','Recentes','Ação','Aventura','Comédia','Terror','Animação']} favorites={favorites} onOpen={openContent} onFavorite={toggleFavorite} />}
  {view === 'Séries' && <Library title="Séries" items={series} categories={['Todas','Populares','Recentes','Drama','Thriller','Documentário']} favorites={favorites} onOpen={openContent} onFavorite={toggleFavorite} />}
  {view === 'Favoritos' && <Library title="Minha lista" items={[...movies, ...series]} categories={['Todos','Filmes','Séries']} favorites={favorites} onOpen={openContent} onFavorite={toggleFavorite} />}
  {view === 'Canais' && <section className="page-section"><p className="eyebrow">PROGRAMAÇÃO AO VIVO</p><h1>Guia de canais</h1><div className="channel-layout"><div><Rail title="Ao vivo agora">{mockChannels.slice(0, 10).map(x => <ChannelCard key={x.id} channel={x} onOpen={() => start(x)} />)}</Rail><Rail title="Todos os canais">{mockChannels.slice(10).map(x => <ChannelCard key={x.id} channel={x} onOpen={() => start(x)} />)}</Rail></div><div className="epg"><h2>Guia de programação</h2>{mockChannels.slice(0, 7).map(x => <button key={x.id} className="epg-row focusable" onClick={() => start(x)}><span className="epg-logo">{x.name.slice(0, 2)}</span><span><strong>{x.name}</strong><small>{x.current}</small></span><span className="epg-time">{x.schedule}<i style={{ width: `${x.progress}%` }} /></span></button>)}</div></div></section>}
  {view === 'Pesquisa' && <section className="page-section"><p className="eyebrow">ENCONTRE SUA PRÓXIMA HISTÓRIA</p><h1>Pesquisar conteúdo</h1><input autoFocus className="search-input focusable" value={query} onChange={e => setQuery(e.target.value)} placeholder="Filmes, séries ou canais..." />{query ? <>{[['Filmes', searchResults.movies], ['Séries', searchResults.series]].map(([title, list]) => <Rail key={title as string} title={`${title} (${(list as AnyContent[]).length})`}>{(list as AnyContent[]).map(x => <MediaCard key={x.id} item={x as Movie} onOpen={() => openContent(x)} favorite={favorites.includes(x.id)} onFavorite={() => toggleFavorite(x.id)} />)}</Rail>)}<Rail title={`Canais (${searchResults.channels.length})`}>{searchResults.channels.map(x => <ChannelCard key={x.id} channel={x} onOpen={() => start(x)} />)}</Rail></> : <div className="empty-state">Digite para pesquisar em todo o CirclePlay.</div>}</section>}
  {view === 'Configurações' && <section className="page-section"><p className="eyebrow">PREFERÊNCIAS</p><h1>Configurações</h1><div className="settings-list"><div><strong>Perfil atual</strong><span>Marina Pessoa</span></div><div><strong>Qualidade de reprodução</strong><span>Automática</span></div><div><strong>Navegação TV-first</strong><span>Controles direcionais ativos</span></div></div></section>}
  </section>
  {selected && <Detail item={selected} favorite={favorites.includes(selected.id)} onFavorite={() => toggleFavorite(selected.id)} onClose={() => setSelected(null)} onPlay={() => start(selected as Movie | Series)} season={season} setSeason={setSeason} />}
  {player && <Player source={player} channelIndex={channelIndex} setChannelIndex={setChannelIndex} onClose={() => setPlayer(null)} />}
  </main>
}

function Library({ title, items, categories, favorites, onOpen, onFavorite }: { title: string; items: (Movie | Series)[]; categories: string[]; favorites: string[]; onOpen: (x: AnyContent) => void; onFavorite: (id: string) => void }) { return <section className="page-section"><p className="eyebrow">CATÁLOGO CIRCLEPLAY</p><h1>{title}</h1><div className="category-tabs">{categories.map((x, i) => <button key={x} className={`focusable ${i === 0 ? 'active' : ''}`}>{x}</button>)}</div><div className="content-grid">{items.map(x => <MediaCard key={x.id} item={x} onOpen={() => onOpen(x)} favorite={favorites.includes(x.id)} onFavorite={() => onFavorite(x.id)} />)}</div></section> }
function Detail({ item, favorite, onFavorite, onClose, onPlay, season, setSeason }: { item: AnyContent; favorite: boolean; onFavorite: () => void; onClose: () => void; onPlay: () => void; season: number; setSeason: (x: number) => void }) { const series = 'episodes' in item ? item as Series : null; return <div className="modal-backdrop" onClick={onClose}><section className="detail-modal" onClick={e => e.stopPropagation()}><button className="close-button focusable" onClick={onClose}>×</button><div className="detail-art" style={{ backgroundImage: `url(${item.image})` }} /><div className="detail-copy"><span className="eyebrow">{'episodes' in item ? 'SÉRIE' : 'FILME'}</span><h1>{item.title}</h1><p className="hero-meta">{item.year} · {'episodes' in item ? `${item.seasons} temporadas` : formatDuration(item.duration)} · {item.genre}</p><p>{item.description}</p><div className="detail-actions"><button className="primary-button focusable" onClick={onPlay}>▶&nbsp; {item.progress ? 'Continuar' : 'Assistir'}</button><button className="secondary-button focusable" onClick={onFavorite}>{favorite ? '★ Favorito' : '☆ Favoritar'}</button></div>{series && <div className="episodes"><div className="season-tabs">{Array.from({ length: series.seasons }, (_, i) => <button key={i} className={`focusable ${season === i + 1 ? 'active' : ''}`} onClick={() => setSeason(i + 1)}>Temporada {i + 1}</button>)}</div>{series.episodes.filter(e => e.season === season).map(e => <button className="episode-row focusable" key={e.id} onClick={onPlay}><img src={e.image} alt="" /><span><strong>{e.number}. {e.title}</strong><small>{formatDuration(e.duration)} · {e.watched ? 'Assistido' : e.progress ? 'Em andamento' : 'Não assistido'}</small></span><span>▶</span></button>)}</div>}</div></section></div> }
function Player({ source, channelIndex, setChannelIndex, onClose }: { source: MediaSource; channelIndex: number; setChannelIndex: (x: number) => void; onClose: () => void }) { const channel = source.type === 'channel' ? mockChannels[channelIndex] : null; return <div className="player" role="dialog" aria-label="Player CirclePlay"><div className="player-screen" style={{ backgroundImage: `linear-gradient(0deg, rgba(7,11,20,.94), rgba(7,11,20,.12)), url(${channel?.image || source.poster})` }}><button className="close-button focusable" onClick={onClose}>×</button><div className="player-label"><span className="live-dot">{channel ? 'AO VIVO' : 'REPRODUZINDO'}</span><h2>{channel?.name || source.title}</h2>{channel && <p>{channel.current} · Próximo: {channel.next}</p>}</div><div className="player-controls"><button className="focusable">▶</button><div className="player-progress"><span /></div><span>{channel ? 'AO VIVO' : '01:12:38'}</span><button className="focusable">🔊</button><button className="focusable">Tela cheia</button></div>{channel && <div className="channel-switcher"><button className="focusable" onClick={() => setChannelIndex(Math.max(0, channelIndex - 1))}>↑ Anterior</button><strong>{channel.name}</strong><button className="focusable" onClick={() => setChannelIndex(Math.min(mockChannels.length - 1, channelIndex + 1))}>↓ Próximo</button></div>}</div></div> }
