export type MediaType = 'movie' | 'series' | 'channel'
export type Movie = { id: string; title: string; year: number; duration: number; genre: string; category: string; description: string; image: string; progress?: number; badge?: string }
export type Episode = { id: string; season: number; number: number; title: string; duration: number; image: string; progress?: number; watched?: boolean }
export type Series = Movie & { seasons: number; episodes: Episode[] }
export type Channel = { id: string; name: string; category: string; image: string; status: 'live' | 'upcoming'; streamUrl: string; current: string; next: string; schedule: string; progress: number }

const images = ['photo-1534447677768-be436bb09401','photo-1614728263952-84ea256f9679','photo-1519608487953-e999c86e7455','photo-1469474968028-56623f02e42e','photo-1511497584788-876760111969','photo-1483347756197-71ef80e95f73','photo-1500530855697-b586d89ba3ee','photo-1504711434969-e33886168f5c']
const image = (index: number, width = 900) => `https://images.unsplash.com/${images[index % images.length]}?auto=format&fit=crop&w=${width}&q=80`
const movieTitles = ['Aurora de Vidro','Horizonte Marte','Linha de Fuga','Sinais do Norte','A Última Estação','Cidade Invisível','Maré Alta','O Código Azul','Depois do Sol','Vértice','Nômades','O Jardim Secreto','Rota 66','A Grande Travessia','Luz de Inverno','Entre Mundos','O Arquivo','Sete Vidas','A Ponte','O Último Sinal','Plano B','Queda Livre','Além do Mapa','Casa de Papel','Noite Sem Fim','Ponto de Encontro','Frequência','O Farol','Tempo Suspenso','A Origem']
const genres = ['Ficção científica','Aventura','Ação','Drama','Comédia','Terror','Animação','Documentário','Thriller','Fantasia']
export const mockMovies: Movie[] = movieTitles.map((title, index) => ({ id: `movie-${index + 1}`, title, year: 2024 - (index % 5), duration: 92 + (index * 7) % 68, genre: genres[index % genres.length], category: ['Populares','Recentes','Ação','Comédia','Terror','Animação'][index % 6], description: `Uma história marcante sobre escolhas, encontros e o que existe depois do horizonte.`, image: image(index), progress: [2, 5, 9].includes(index) ? 22 + index * 7 : undefined, badge: index === 0 ? 'Destaque' : index < 3 ? 'Popular' : undefined }))
const seriesTitles = ['Depois da Noite','Oceano Profundo','Distrito 9','Círculo de Fogo','Arquivos do Amanhã','A Casa Verde','Fronteiras','Ponto Cego','Ventos do Norte','Código Fantasma','Horizonte','A Colônia','Ecos','Linha do Tempo','Conexão']
export const mockSeries: Series[] = seriesTitles.map((title, index) => ({ ...mockMovies[index + 2], id: `series-${index + 1}`, title, type: undefined as never, seasons: 2 + index % 3, category: index % 2 ? 'Drama' : 'Populares', episodes: Array.from({ length: 12 }, (_, episode) => ({ id: `ep-${index}-${episode}`, season: Math.floor(episode / 4) + 1, number: (episode % 4) + 1, title: `Episódio ${(episode % 4) + 1} — ${['O começo','Sinais','A travessia','Retorno'][episode % 4]}`, duration: 42 + episode % 8, image: image(index + episode), progress: episode === 0 && index < 4 ? 48 : undefined, watched: episode < index % 3 })) }))
const channelNames = ['Jornal 24h','Arena Sports','Cultura+','Kids Club','Cinema Classic','Mundo News','Futebol Total','Natureza Viva','Séries Agora','Discovery Brasil','Música Pop','Documenta','Comedy House','Infantil Play','Tech Channel','Drama Max','Viagem+','Brasil ao Vivo','Retro TV','Esporte News']
export const mockChannels: Channel[] = channelNames.map((name, index) => ({ id: `channel-${index + 1}`, name, category: ['Notícias','Esportes','Filmes','Séries','Entretenimento','Infantil','Documentários'][index % 7], image: image(index + 3, 700), status: index < 12 ? 'live' : 'upcoming', streamUrl: `mock://stream/${index + 1}`, current: ['Plantão CirclePlay','Jogo ao vivo','Sessão da tarde','Episódio especial'][index % 4], next: ['Boletim das 18h','Melhores momentos','O próximo capítulo','Jornal da noite'][index % 4], schedule: `${17 + index % 5}:00 — ${18 + index % 5}:30`, progress: 20 + (index * 9) % 70 }))
export const contentService = { async getMovies() { return mockMovies }, async getSeries() { return mockSeries }, async getChannels() { return mockChannels }, async searchContent(query: string) { const q = query.toLowerCase(); return { movies: mockMovies.filter(x => x.title.toLowerCase().includes(q)), series: mockSeries.filter(x => x.title.toLowerCase().includes(q)), channels: mockChannels.filter(x => x.name.toLowerCase().includes(q)) } }, async getMovieDetails(id: string) { return mockMovies.find(x => x.id === id) }, async getSeriesDetails(id: string) { return mockSeries.find(x => x.id === id) }, async getEpisodes(id: string) { return mockSeries.find(x => x.id === id)?.episodes ?? [] }, async getChannelsSchedule() { return mockChannels } }
export type AnyContent = Movie | Series | Channel
export const formatDuration = (minutes: number) => `${Math.floor(minutes / 60)}h ${minutes % 60}min`
export const poster = image
